### ISSUE TITLE
windows defender считает вирусом

### ISSUE THREAD

**Issue by Persivan** [Devyatyi9/usm_sbt_patcher#3]
![image](https://github.com/Devyatyi9/HI3rd_usm_sbt_patcher/assets/39733368/a29b5c4d-fcc8-4e97-8b5a-cc134d44c192)
пупупууууу

Первый раз заметил 31 мая 2024 года. До этого было все ок (последний раз запускал +- 20 мая). Сейчас не удается ни скачать, ни запустить скачанный ранее (еще и файл удалила((( ). 
Помню, что винда отлавливает файлы по названию и не позволяет запускать их. Где-то в дискорде писал об этом. Когда переименовывал эту прогу.

**Comment by Persivan** [comment]
Попробуй поменять сигнатуру файла с помощью анти-антивирусного ПО)))

**Comment by Devyatyi9** [comment]
Оно же вроде типа шифрует какие-то части данных?
Не пойму почему раньше у тебя там всё нормально было)
я думал у тебя другая ошибка была, типа: сайт скачан откуда-то из интернета и т.д.
когда надо галочку на разрешить в свойствах ставить.

**Comment by Devyatyi9** [comment]
Нужно будет попробовать обновить проект под последнюю версию библиотек и проверить не будет ли ошибок. Может быть это поможет.
